services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -lc "rm -f tmp/pids/server.pid && bundle exec rdbg --open --sock-path /tmp/rdbg -- bin/rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      BUNDLE_DEPLOYMENT: "0"
      BUNDLE_FROZEN: "0"
    stdin_open: true   # ajuda no TTY interativo
    tty: true


volumes:
  db_data:
  bundle:
